### ISSUE TITLE
change styling to fit logstash.net

### ISSUE THREAD

**Issue by optikfluffel** [logstash/cookbook#11]
hi :)
how about changing the whole theme that is matches [logstash.net](http://logstash.net/) and integrates seamless into it?
i could give it a try if you don't actually want it to look that different and dark ^^

**Comment by jordansissel** [comment]
I'm not much of a fan of logstash.net's current design either. The styling for the cookbook is an ongoing experiment. First step perhaps is to try lighter background colors or something like that.

**Comment by optikfluffel** [comment]
oh I need a new project to procrastinate on xD if you don't mind I could try restyling it and make a few drafts ^^ but I would totally understand if you want to do it yourself and have control about it etc.. do you have anything in mind yet? what don't you like there?
