### ISSUE TITLE
date format in http://cookbook.logstash.net/recipes/apache-json-logs/

### ISSUE THREAD

**Issue by pippoppo** [logstash/cookbook#9]
Hi,
timestamp format seems wrong, elasticsearch doesn't like it.
This is the recipe:
LogFormat "{ \"@timestamp\": \"%{%Y/%m/%dT%H:%M:%S%z}t\"
but shouldn't it be
LogFormat "{ \"@timestamp\": \"%{%Y-%m-%dT%H:%M:%S%z}t\" ?

I like this cookbook, but also would love a working example of a filter allowing to skip all 200 statuses. I tried but couldn't succeed in grepping the status field...

thanks

**Comment by jordansissel** [comment]
Ahh, so, skipping '200' status should work like this:

```
filter {
  grep {
    match => [ "response", "^200$" ]
    negate => true 
  }
}
```

If this doesn't work, let me know! :)

**Comment by pippoppo** [comment]
Thanks!!
